services:
  bot: 
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aiogram_bot
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - aiogram_bot

  postgres:
    restart: always
    image: postgres:13
    container_name: aiogram_bot_postgres
    volumes:
      - aiogram_bot_postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - aiogram_bot

volumes:
  aiogram_bot_postgres_data:

networks:
  aiogram_bot:
    driver: bridge
